---
sudo: required
dist: xenial
language: python
python:
  - 3.6
cache:
  pip: true
before_install:
  - curl -Lo footloose https://github.com/weaveworks/footloose/releases/download/0.6.2/footloose-0.6.2-linux-x86_64
  - chmod +x footloose
  - sudo mv footloose /usr/local/bin/
install:
  - sudo pip install tox
script:
  - tox -e ci
