---
- hosts: localhost
  connection: local
  pre_tasks:
    - name: Install bases packages with apt
      sudo: yes
      apt:
         name={{ item }}
         state=latest
         update_cache=yes
      with_items:
        - wget
        - curl
        - python-pip
      when: ansible_os_family == 'Debian'
  roles:
    - common
    - docker
    - java
    - pycharm
