---
- hosts: all
  roles:
    # - common
    - {role: bat, tags: ['bat']}
    - {role: chezmoi, tags: ['chezmoi']}
    - {role: dive, tags: ['dive']}
    # - docker
    - {role: exa, tags: ['exa']}
    - {role: fzf, tags: ['fzf']}
    - {role: footloose, tags: ['footloose']}
    #  - java
    #  - dbeaver
    - {role: drawio, tags: ['drawio']}
    #  - intellj
    - {role: kind, tags: ['kind']}
    - {role: kubefwd, tags: ['kubefwd']}
    - {role: k9s, tags: ['k9s']}
    - {role: lazydocker, tags: ['lazydocker']}
    - {role: lazygit, tags: ['lazygit']}
    #  - maven
    - {role: octant, tags: ['octant']}
    - {role: powerline-go, tags: ['powerline-go']}
    #  - pycharm
    - {role: sshed, tags: ['sshed']}
    - {role: vscodium, tags: ['vscodium']}
    - {role: ytop, tags: ['ytop']}
