---
- hosts: all
  become: yes
  pre_tasks:
    - name: Install bases packages with apt
      become: yes
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - wget
        - curl
        - python-pip
        - tar
        - unzip
      when: ansible_os_family == 'Debian'
  roles:
    - common
# - docker
    - sshed
    - lazygit
    - java
# - maven
    - pycharm
    - intellj
    - powerline-go
    - vscodium
    - zeal
# - dbeaver
