---
- hosts: all
  roles:
    # - common
    - {role: aqua, tags: ['aqua']}
    - {role: bat, tags: ['bat']}
    - {role: chezmoi, tags: ['chezmoi']}
    - {role: code-server, tags: ['code-server']}
    - {role: dive, tags: ['dive']}
    # - docker
    - {role: exa, tags: ['exa']}
    - {role: fzf, tags: ['fzf']}
    - {role: footloose, tags: ['footloose']}
    #  - java
    #  - dbeaver
    - {role: drawio, tags: ['drawio']}
    #  - intellj
    - {role: glab, tags: ['glab']}
    - {role: karto, tags: ['karto']}
    - {role: kind, tags: ['kind']}
    - {role: kubefwd, tags: ['kubefwd']}
    - {role: k9s, tags: ['k9s']}
    - {role: kubectl, tags: ['kubectl']}
    - {role: lazydocker, tags: ['lazydocker']}
    - {role: lazygit, tags: ['lazygit']}
    - {role: lens, tags: ['lens']}
    - {role: gitlab-ci-local, tags: ['gitlab-ci-local']}
    # - {role: golang, tags: ['golang']}
    - {role: marp-cli, tags: ['marp-cli']}
    #  - maven
    - {role: octant, tags: ['octant']}
    - {role: popeye, tags: ['popeye']}
    - {role: powerline-go, tags: ['powerline-go']}
    - {role: pluto, tags: ['pluto']}
    #  - pycharm
    - {role: sshed, tags: ['sshed']}
    - {role: sshs, tags: ['sshs']}
    - {role: taskctl, tags: ['taskctl']}
    - {role: vscodium, tags: ['vscodium']}
    - {role: ytop, tags: ['ytop']}
