---
- name: create the installation directory for DBeaver
  file: path={{ dbeaver_installation_directory }}
        state=directory
  tags:
    - dbeaver

- name: create the directory where dbeaver will be untarred
  file: path={{ dbeaver_tar_directory }}
        state=directory
  tags:
    - dbeaver

- name: download latest version of DBeaver (64-bit)
  uri: url={{ dbeaver_url_64 }}
       dest=~/{{ dbeaver_file }}
       creates=~/{{ dbeaver_file }}
  when: ansible_architecture == "x86_64"
  tags:
    - dbeaver

- name: download latest version of DBeaver (32-bit)
  uri: url={{ dbeaver_url_32 }}
       dest=~/{{ dbeaver_file }}
       creates=~/{{ dbeaver_file }}
  when: ansible_architecture == "i386"
  tags:
    - dbeaver

- name: untar the downloaded DBeaver archive
  unarchive: copy=no
             src=~/{{ dbeaver_file }}
             dest={{ dbeaver_tar_directory }}
             creates={{ dbeaver_home_directory }}
  register: unarchive_result
  tags:
    - dbeaver

- name: move the untarred files to the standard location
  command: mv {{ dbeaver_tar_directory }}
           {{ dbeaver_home_directory }}
  when: unarchive_result | changed
  tags:
    - dbeaver

- name: create a pretty symlink pointing to the most recent version
  file: src={{ dbeaver_home_directory }}
        path={{ dbeaver_installation_directory }}/latest
        state=link
  tags:
    - dbeaver

- name: add a launcher to the development menu for DBeaver
  copy: src=../files/dbeaver.desktop
        dest=/usr/share/applications
  tags:
    - dbeaver
