- name: Download Pycharm
  get_url: 
    url=http://download.jetbrains.com/python/pycharm-community-4.5.1.tar.gz
    dest=/tmp/
  tags:
    - pycharm

- name: Install Pycharm
  sudo: yes
  shell: tar -xvzf /tmp/pycharm-community-4.5.1.tar.gz -C /opt
  tags:
    - pycharm

- name: Change rights on Pycharm
  sudo: yes
  shell: chmod -R +r /opt/pycharm-community-4.5.1
  tags:
    - pycharm

- name: Add Pycharm on directory /etc/profile.d 
  sudo: yes
  shell: ln -s /opt/pycharm-community-4.5.1/bin/pycharm.sh /usr/local/bin/
  tags:
    - pycharm
