---
- name: popeye | download and install popeye
  unarchive:
    src: "{{ popeye_url }}"
    dest: "{{ popeye_destination }}"
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  tags:
    - popeye
