---
- name: Download maven binary
  get_url:
    url: http://mirrors.standaloneinstaller.com/apache/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.zip
    dest: /tmp/maven_{{version}}.zip
  tags:
    - maven

- name: Unarchive maven binary
  unarchive:
    src: /tmp/maven_{{version}}.zip
    dest: /opt
    creates: /opt/apache-maven-{{version}}/maven
    copy: no
  become: yes
  tags:
    - maven

- name: Create link from /opt/maven to the maven versionned directory
  file:
    dest: /opt/maven
    src: /opt/apache-maven-{{version}}
    force: yes
    state: link
  become: yes
  tags:
    - maven

- name: Adding maven command to user path
  file:
    src: /opt/maven/bin/mvn
    dest: /usr/bin/mvn
    state: link
  become: yes
  tags:
    - maven
