---
- name: zeal | add Zeal ppa
  apt_repository:
    repo: "ppa:zeal-developers/ppa"
    state: present
  tags:
    - zeal

- name: zeal | install zeal
  apt:
    name: zeal
    state: present
    update_cache: true
  tags:
    - zeal
