---
- name: Destroy
  hosts: localhost
  gather_facts: false
  tasks:
    - name: destroy vm
      shell: footloose delete
      ignore_errors: yes
    - name: remove keys
      file:
        path: "{{ playbook_dir }}/{{ item }}"
        state: absent
      ignore_errors: yes
      loop:
        - cluster-key
        - cluster-key.pub
