---
dependency:
  name: galaxy
  enabled: False
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: workstation-node0
    groups:
      - molecule
      - all
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ["301", "305"]
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  playbooks:
    converge: ../../workstation.yml
scenario:
  name: default
verifier:
  name: testinfra
  options:
    junit-xml: report.xml
  lint:
    name: flake8
