---
- name: fzf | download and install fzf
  unarchive:
    src: "{{ fzf_url }}"
    dest: "{{ fzf_destination }}"
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  tags:
    - fzf
