- name: Install common packages with apt
  become: yes
  apt:
     name={{ item }}
     state=latest
     update_cache=yes
  with_items:
    - git
    - git-gui
    - htop
    - zip
    - unzip
    - vim
    - terminator
    - tmux
    - zsh
    - python-dev
    - python-pip
    - libffi-dev
    - libssl-dev
    - keepassx
    - sshpass
  when: ansible_os_family == 'Debian'

- name: Install common packages with pip
  become: yes
  pip:
    name={{ item }}
    state=latest
  with_items:
    - ansible
    - git-up
    - httpie
    - virtualenv
    - virtualenvwrapper
    - magpie
    - pdb
    - tox
    - testrepository

  when: ansible_os_family == 'Debian'

- name: Install docker-compose
  become: yes
  pip:
    name=docker-compose
    version=1.2.0
  when: ansible_os_family == 'Debian'
