---
- name: Install common packages with apt
  become: yes
  apt:
     name={{ item }}
     state=present
     update_cache=yes
  loop:
     - git
     - git-gui
     - htop
     - zip
     - unzip
     - vim
     - terminator
     - tmux
     - zsh
     - python3-dev
     - python3-pip
     - libffi-dev
     - libssl-dev
     - sshpass
     - zeal
  when: ansible_os_family == 'Debian'
  tags:
     - role::common

- name: Install common packages with pip
  become: yes
  pip:
     name: "{{ item }}"
     state: present
  loop:
     - ansible
     - git-up
     - httpie
     - virtualenv
     - virtualenvwrapper
     - tox
     - pipdeptree
  when: ansible_os_family == 'Debian'
  tags:
     - role::common

- name: Install docker-compose
  become: yes
  pip:
     name: docker-compose
  when: ansible_os_family == 'Debian'
  tags:
     - role::common
