- name: Load docker setup file and install
  shell: curl -sSL https://get.docker.com/ | sh
  tags:
    - docker

- name: Check if logrotate configuration for docker exists
  stat:
    path: "/etc/logrotate.d/docker-container"
  register: logrotate_docker_status

- name: configure logrotate for docker
  copy:
    src: docker-container
    dest: /etc/logrotate.d/docker-container
    owner: root
    mode: 0644
  notify:
      - "restart logrotate"
  when: not logrotate_docker_status.stat.exists

- name: Create Docker group
  group:
    name: docker
    state: present
  become: yes
  when: ansible_os_family == 'Debian'
  tags:
    - docker

- name: Add current user to docker group
  user:
    name: "{{ansible_user}}"
    groups: docker
    append: yes
  become: yes
  when: ansible_os_family == 'Debian'
  tags:
    - docker
